<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FlamingBase\Form\Element\DateTimePicker'               => __DIR__ . '/src/FlamingBase/Form/Element/DateTimePicker.php',
    'FlamingBase\Form\View\Helper\FormElementErrors'        => __DIR__ . '/src/FlamingBase/Form/View/Helper/FormElementErrors.php',
    'FlamingBase\Form\View\Helper\DoctrineEntitySelectInit' => __DIR__ . '/src/FlamingBase/Form/View/Helper/DoctrineEntitySelectInit.php',
    'FlamingBase\Form\View\Helper\FormRow'                  => __DIR__ . '/src/FlamingBase/Form/View/Helper/FormRow.php',
    'FlamingBase\Service\AbstractService'                   => __DIR__ . '/src/FlamingBase/Service/AbstractService.php',
    'FlamingBase\View\Helper\FlashMessenger'                => __DIR__ . '/src/FlamingBase/View/Helper/FlashMessenger.php',
    'FlamingBase\View\Helper\BootstrapifyMenu'              => __DIR__ . '/src/FlamingBase/View/Helper/BootstrapifyMenu.php',
    'FlamingBase\View\Helper\Ellipsis'                      => __DIR__ . '/src/FlamingBase/View/Helper/Ellipsis.php',
    'FlamingBase\Validator\UniqueObject'                    => __DIR__ . '/src/FlamingBase/Validator/UniqueObject.php',
    'FlamingBase\Controller\AbstractCliController'          => __DIR__ . '/src/FlamingBase/Controller/AbstractCliController.php',
    'FlamingBase\Controller\Plugin\EnvInfo'                 => __DIR__ . '/src/FlamingBase/Controller/Plugin/EnvInfo.php',
    'FlamingBase\Controller\Plugin\Emailer'                 => __DIR__ . '/src/FlamingBase/Controller/Plugin/Emailer.php',
    'FlamingBase\Stdlib\Hydrator\Strategy\DoctrineObject'   => __DIR__ . '/src/FlamingBase/Stdlib/Hydrator/Strategy/DoctrineObject.php',
    'FlamingBase\Stdlib\StringTool'                         => __DIR__ . '/src/FlamingBase/Stdlib/StringTool.php',
    'FlamingBase\Stdlib\ImageTool'                          => __DIR__ . '/src/FlamingBase/Stdlib/ImageTool.php',
    'FlamingBase\Entity\AbstractEntity'                     => __DIR__ . '/src/FlamingBase/Entity/AbstractEntity.php',
    'FlamingBase\Module'                                    => __DIR__ . '/Module.php',
    'FlamingBaseTest\Entity\ConcreteEntity'                 => __DIR__ . '/test/FlamingBaseTest/Entity/ConcreteEntity.php',
    'FlamingBaseTest\Entity\AbstractEntityTest'             => __DIR__ . '/test/FlamingBaseTest/Entity/AbstractEntityTest.php',
    'FlamingBaseTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
);
